Added a ceph dashboard proposal with cloud selector
infrawatch/dashboards pull request #26
Opened 2021-04-09 10:53 UTC by josecastillolema

2021-07-12 13:03 UTC, leifmadsen commented
Thanks very much for the submission. We're getting to the point (finally :)) to have a base configuration to target dashboards against for STF 1.3. Hopefully we can test/refine/merge this in the next couple of weeks as we've been doing dashboard work recently.

2021-07-12 13:27 UTC, pleimer commented
Can you wrap this in a GrafanaDashboard custom resource object like https://github.com/infrawatch/dashboards/blob/master/deploy/rhos-dashboard.yaml? It makes it easier to load and view changes

2021-07-12 13:28 UTC, pleimer requested changes
Thanks for this! Can you wrap this in a GrafanaDashboard custom resource object like https://github.com/infrawatch/dashboards/blob/master/deploy/rhos-dashboard.yaml? It makes it easier to load and view changes

2021-07-12 13:37 UTC, josecastillolema commented
Done @pleimer !
Dashboard wrapped into a GrafanaDashboard custom resource object.

2021-07-12 13:43 UTC, leifmadsen commented
Wow that was quick :)  Thanks! Maybe we can do a bit of testing this week and see how close it is.

2021-07-15 19:18 UTC, leifmadsen commented
I had to do a bit of changing around because the format I have doesn't seem to align to what you have around the metrics. Overall the dashboard does look pretty good for the functionality that I have available to me and the data I'm passing.

Do you have a copy of your OSP configuration for the collectd Ceph plugin? You're using a few metrics/labels that I don't have access to, and I'd like to try and align our base configuration so that things all work out of the box. Thanks @josecastillolema !

2021-07-16 18:25 UTC, josecastillolema commented
The OSP configuration file (from RHOSP13):
```
parameter_defaults:
  EventPipelinePublishers: []
  MetricPipelinePublishers: []
  PipelinePublishers: []
  ManagePipeline: true
  ManagePolling: true
  CeilometerEnablePanko: false
  CeilometerQdrPublishEvents: true
  CeilometerQdrPublishMetrics: true
  CeilometerQdrEventsConfig:
    driver: amqp
    topic: labnk-event
  CeilometerQdrMetricsConfig:
    driver: amqp
    topic: labnk-metering
  CollectdAmqpInstances:
    labnk-notify:
      format: JSON
      notify: true
      presettle: false
    labnk-telemetry:
      format: JSON
      presettle: false
  CollectdAmqpInterval: 30
  CollectdConnectionType: amqp1
  CollectdDefaultPlugins:
    - ceph
    - cpu
    - df
    - disk
    - hugepages
    - interface
    - load
    - memory
    - unixsock
    - ovs_stats
    - uptime
  CollectdDefaultPollingInterval: 30
  MetricsQdrAddresses:
    - distribution: multicast
      prefix: collectd
    - distribution: multicast
      prefix: anycast/ceilometer
  MetricsQdrConnectors:
    - host: default-interconnect-...
      port: 443
      role: edge
      sslProfile: sslProfile
      verifyHostname: false
  MetricsQdrSSLProfiles:
    - name: sslProfile
  ExtraConfig:
    ceilometer::agent::polling::polling_interval: 30
    collectd::plugin::cpu::reportbycpu: true
    collectd::plugin::cpu::reportbystate: true
    collectd::plugin::cpu::reportnumcpu: true
    collectd::plugin::cpu::valuespercentage: true
    collectd::plugin::df::ignoreselected: true
    collectd::plugin::df::reportbydevice: true
    collectd::plugin::df::fstypes: ['xfs']
    collectd::plugin::load::reportrelative: true
    collectd::plugin::virt::connection: "qemu:///system"
    collectd::plugin::virt::extra_stats: "cpu_util disk disk_err pcpu job_stats_background perf vcpupin vcpu memory domain_state"
    collectd::plugin::virt::hostname_format: "hostname name uuid"
    collectd::plugin::vmem::verbose: true
    collectd::plugin::virt::plugin_instance_format: metadata
    collectd::plugin::ovs_stats::socket: '/run/openvswitch/db.sock'
    collectd::plugin::ceph::daemons:
    - ceph-mon.lab01nkpcr003
    - ceph-mon.lab01nkpcr004
    - ceph-mon.lab01nkpcr006
    - ceph-osd.0
    - ceph-osd.1
    - ceph-osd.2
    - ceph-osd.3
    - ceph-osd.4
    - ceph-osd.5
    - ceph-osd.6
    - ceph-osd.7
    - ceph-osd.8
    - ceph-osd.9
    - ceph-osd.10
    - ceph-osd.11
    - ceph-osd.12
    - ceph-osd.13
    - ceph-osd.14
    - ceph-osd.15
```

2021-07-21 15:34 UTC, leifmadsen commented
Confirmed this is working as-is once you have the MONs reporting data as well. I have an open issue to identify documentation that allows deployment of OSP in such a way that the `ceph` plugin is scheduled for deployment on the controller nodes. (See https://bugzilla.redhat.com/show_bug.cgi?id=1984193)

I might also go through an O'Reilly book I found about monitoring Ceph and see about enhancing the dashboard based on their recommendations, including adding CPU and memory load information for the Ceph services.

2021-07-21 15:35 UTC, leifmadsen approved these changes

2021-07-21 15:37 UTC, leifmadsen commented on contrib/ceph-dashboard.yaml
> +              "value": "default-labnk-coll-meter-smartgateway"
```suggestion
              "text": "",
              "value": ""
```

2021-07-21 19:58 UTC, leifmadsen commented
I've made a few changes and updated according to some of our current approaches. I'm going to close this one in favour of #33 which is still based on your work.

2021-07-21 19:58 UTC, closed without merging