Move Uptime panel backends to Prometheus
infrawatch/dashboards pull request #28
Opened 2021-07-06 21:13 UTC by pleimer

https://github.com/infrawatch/service-telemetry-operator/pull/225 moves storage of API stats from Elasticsearch to Prometheus. This patch adjusts relevant panels to work with the change

2021-07-07 14:51 UTC, csibbitt approved these changes
These are pretty rough to review without loading them up. If we're going to stay in the dashboard business we should consider one of the concise DSLs.

I didn't test this, but it follows the other work I've been reviewing and looks roughly correct from here

2021-07-07 14:51 UTC, csibbitt commented on deploy/rhos-cloud-dashboard.yaml
> +          "datasource": null,
Is this what we want? I assume "null" mean "default datasource" - it would be better to name it explicitly

2021-07-07 14:51 UTC, csibbitt commented on deploy/rhos-cloud-dashboard.yaml
> +        "from": "now-3h",
My preferred default might be 24h?

2021-07-07 20:01 UTC, pleimer commented on deploy/rhos-cloud-dashboard.yaml
> +          "datasource": null,
You're correct it does mean default which for us is STFPrometheus. Making adjustments and exporting in a GUI makes it harder to track little discrepancies like this, it would be nice to use one of the DSLs to describe the dashboards, just will be a lot of work that's going to require at least a full sprint. I have a PoC using jsonnet that works with the grafana operator

2021-07-07 20:02 UTC, pleimer commented on deploy/rhos-cloud-dashboard.yaml
> +        "from": "now-3h",
hmm yeah

2021-07-09 11:56 UTC, leifmadsen commented on deploy/rhos-cloud-dashboard.yaml
> +          "datasource": null,
I think I agree we should call this out specifically since we've identified it here.

2021-07-09 19:41 UTC, pleimer commented
Since this update will break dashboards for 1.2, I created directories to host 1.2 and 1.3 dashboards separately. This is going to make it impossible to review, but just DM for a link if you want to see the dashboards.

2021-07-12 13:01 UTC, leifmadsen requested changes
The one issue we have with the move is that the STF 1.2 and 1.3 docs need to be adjusted because the paths of the dashboards are changing. I'm not sure if this is acceptable during the STF 1.2 phase.

I think I'd leave the existing dashboards where they are in the meantime, and then create 1.3 and in the future 1.4 dashboards. Once STF 1.4 comes out, then we can drop the 1.2 dashboards from the main repository.

We can also talk to Joanne and see if there is something we can do in documentation and release notes when things like this change, but for now, I think we have to leave the 1.2 dashboards in place (or symlink them back to the original location if that is possible so we don't break the documentation).

2021-07-12 16:54 UTC, leifmadsen approved these changes

2021-07-13 19:35 UTC, merged